version: "2.3"
services:
  pg_seico_backend:
    build: './database'
    container_name: pg_seico_backend
    restart: always
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data_volumes/pg_volume/:/var/lib/postgresql/data
    networks:
    - databasesnet
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${APP_DB_NAME}", "-U", "${APP_DB_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10

  pgadmin_seico_backend:
    image: dpage/pgadmin4:4.23
    container_name: pgadmin_seico_backend
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    volumes:
        - ./data_volumes/pgadmin_volume:/var/lib/pgadmin
    networks:
        - databasesnet
    depends_on:
        - pg_seico_backend

  IMAGE:
    image: IMAGE
    restart: always
    container_name: IMAGE
    ports:
        - 5000:5000
    volumes:
        - "../:/app"
    networks:
        - databasesnet
    depends_on:
        - pg_seico_backend
    stdin_open: true # docker run -i
    tty: true        # docker run -t

networks:
    databasesnet:
          