FROM jupyter/scipy-notebook
 
RUN mkdir my-model

ENV MODEL_DIR=/home/jovyan/my-model
ENV MODEL_FILE_LDA=clf_lda.joblib
ENV MODEL_FILE_NN=clf_nn.joblib

RUN pip install joblib

COPY ./models/ml/data/train.csv ./train.csv 
COPY ./models/ml/data/trainLabels.csv ./trainLabels.csv

COPY ./models/ml/train.py ./train.py

RUN python3 train.py
